### ISSUE TITLE
UTF16String API updates

### ISSUE THREAD

**Issue by stevengj** [nolta/ICU.jl#12]
In preparation for JuliaLang/julia#7016 or similar changes, you should replace `UTF16String(data)` by `utf16(data)` and `length(s.data)` by `sizeof(s) >> 1`.

**Comment by PallHaraldsson** [comment]
I see "length" "-1" in the code, is this maybe already fixed (in a different way)? Was this forgotten or want to use size? For performance reasons? Length would have to scan the whole string (in case of non-BMP).

**Comment by stevengj** [comment]
Yes, looked like @nolta fixed it in 0cc11e20b0389ba98fa8dc834c7604c469b37b75 without cross-referencing this issue.

The only downside to using `length(s.data)-1` is that it depends on the internal representation of `UTF16String`, so if the NUL-termination is ever removed this will have to change again.
